export type Locale = "hy" | "en" | "ru";
export type ProjectKind = "series" | "film" | "stage" | "children";

export type Project = {
  id: number;
  title: Record<Locale, string>;
  year: string;
  credit: Record<Locale, string>;
  kind: ProjectKind;
  episodes?: number;
  featuredRank?: number;
  featuredDetail?: Record<Locale, string>;
  poster?: string;
  watchUrl?: string;
  watchKind?: "youtube" | "platform";
  seoSlug?: string;
};

export { updatedIso } from "./site-copy.mjs";

export const projects: Project[] = [
  { id: 1, title: { hy: "Օտարը", en: "The Stranger", ru: "Чужой" }, year: "2017", credit: { hy: "99 սերիա", en: "99 episodes", ru: "99 серий" }, kind: "series", episodes: 99, watchUrl: "https://www.youtube.com/watch?v=T6nt8gOKoso", watchKind: "youtube", seoSlug: "the-stranger" },
  { id: 2, title: { hy: "Էլենի օրագիրը", en: "Elen’s Diary", ru: "Дневник Элен" }, year: "2017–2019", credit: { hy: "1-ին եթերաշրջան · 197 սերիա", en: "Season 1 · 197 episodes", ru: "Сезон 1 · 197 серий" }, kind: "series", episodes: 197, featuredRank: 1, featuredDetail: { hy: "2 եթերաշրջան · 421 սերիա", en: "2 seasons · 421 episodes", ru: "2 сезона · 421 серия" }, poster: "/posters/eleni-oragir.webp", watchUrl: "https://www.youtube.com/playlist?list=PLIdKbEnBj_B-mvF0PArmubgCmqOdv9rvT", watchKind: "youtube", seoSlug: "elens-diary" },
  { id: 3, title: { hy: "Էլենի օրագիրը 2", en: "Elen’s Diary 2", ru: "Дневник Элен 2" }, year: "2018–2019", credit: { hy: "224 սերիա", en: "224 episodes", ru: "224 серии" }, kind: "series", episodes: 224, watchUrl: "https://www.youtube.com/watch?v=J9oQAJIiye8", watchKind: "youtube", seoSlug: "elens-diary-2" },
  { id: 4, title: { hy: "Թղթե երազանք", en: "Paper Dream", ru: "Бумажная мечта" }, year: "2019", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, featuredRank: 2, poster: "/posters/tghte-erazank.webp", watchUrl: "https://www.youtube.com/watch?v=iIn9qu4Phls", watchKind: "youtube", seoSlug: "paper-dream" },
  { id: 5, title: { hy: "Երկուսով", en: "Together", ru: "Вдвоём" }, year: "2019–2021", credit: { hy: "198 սերիա", en: "198 episodes", ru: "198 серий" }, kind: "series", episodes: 198, watchUrl: "https://www.youtube.com/watch?v=O06cuvk73MA", watchKind: "youtube", seoSlug: "together" },
  { id: 6, title: { hy: "Խաղալիք", en: "Toy", ru: "Игрушка" }, year: "2021", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=SOc5x1LOROU", watchKind: "youtube", seoSlug: "toy" },
  { id: 7, title: { hy: "Կհանդիպենք անտառի տնակում", en: "We’ll Meet at the Forest Cottage", ru: "Встретимся в лесном домике" }, year: "2021", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, featuredRank: 8, featuredDetail: { hy: "2 մաս · 48 սերիա", en: "2 parts · 48 episodes", ru: "2 части · 48 серий" }, poster: "/posters/antarri-tnakum.webp", watchUrl: "https://www.youtube.com/watch?v=Q-uiVUBPy5k", watchKind: "youtube", seoSlug: "forest-cottage" },
  { id: 8, title: { hy: "Բեկորներ", en: "Fragments", ru: "Осколки" }, year: "2021–2022", credit: { hy: "148 սերիա", en: "148 episodes", ru: "148 серий" }, kind: "series", episodes: 148, watchUrl: "https://www.youtube.com/watch?v=K3kISoAjN28", watchKind: "youtube", seoSlug: "fragments" },
  { id: 9, title: { hy: "Բռնիր ձեռքս", en: "Hold My Hand", ru: "Держи меня за руку" }, year: "2021–2022", credit: { hy: "120 սերիա", en: "120 episodes", ru: "120 серий" }, kind: "series", episodes: 120, watchUrl: "https://www.youtube.com/watch?v=r_UrgYomjhA", watchKind: "youtube", seoSlug: "hold-my-hand" },
  { id: 10, title: { hy: "Երկու քույր ենք", en: "We Are Two Sisters", ru: "Мы две сестры" }, year: "2022", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=QkCO6N7uK-k", watchKind: "youtube", seoSlug: "we-are-two-sisters" },
  { id: 11, title: { hy: "Հատուկ դասարան", en: "Special Class", ru: "Специальный класс" }, year: "2022", credit: { hy: "90–99 սերիա", en: "90–99 episodes", ru: "90–99 серий" }, kind: "series", featuredRank: 4, featuredDetail: { hy: "2 եթերաշրջան", en: "2 seasons", ru: "2 сезона" }, poster: "/posters/hatuk-dasaran.webp", watchUrl: "https://www.youtube.com/watch?v=IycLc4NiGgk", watchKind: "youtube", seoSlug: "special-class" },
  { id: 12, title: { hy: "Հատուկ դասարան 2", en: "Special Class 2", ru: "Специальный класс 2" }, year: "2022–2023", credit: { hy: "140 սերիա", en: "140 episodes", ru: "140 серий" }, kind: "series", episodes: 140, watchUrl: "https://www.youtube.com/watch?v=qYIl-UJXMIM", watchKind: "youtube", seoSlug: "special-class-2" },
  { id: 13, title: { hy: "Ապրիր ինձ հետ", en: "Live With Me", ru: "Живи со мной" }, year: "2022", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://kinodaran.com/hy/title/aprir_indz_het.html", watchKind: "platform", seoSlug: "live-with-me" },
  { id: 14, title: { hy: "Մնա ինձ հետ", en: "Stay With Me", ru: "Останься со мной" }, year: "2022", credit: { hy: "36 սերիա", en: "36 episodes", ru: "36 серий" }, kind: "series", episodes: 36, watchUrl: "https://kinodaran.com/hy/title/mna_indz_het.html", watchKind: "platform", seoSlug: "stay-with-me" },
  { id: 15, title: { hy: "4 երազանք", en: "4 Dreams", ru: "4 мечты" }, year: "2022–2023", credit: { hy: "61 սերիա", en: "61 episodes", ru: "61 серия" }, kind: "series", episodes: 61, watchUrl: "https://www.youtube.com/watch?v=mFPB0EZOt_A", watchKind: "youtube", seoSlug: "4-dreams" },
  { id: 16, title: { hy: "Կհանդիպենք անտառի տնակում 2", en: "We’ll Meet at the Forest Cottage 2", ru: "Встретимся в лесном домике 2" }, year: "2022–2023", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=TgtC8Rmu9u0", watchKind: "youtube", seoSlug: "forest-cottage-2" },
  { id: 17, title: { hy: "Hotel Grand", en: "Hotel Grand", ru: "Отель Гранд" }, year: "2023", credit: { hy: "10 սերիա", en: "10 episodes", ru: "10 серий" }, kind: "series", episodes: 10, featuredRank: 11, featuredDetail: { hy: "3 եթերաշրջան · 34 սերիա", en: "3 seasons · 34 episodes", ru: "3 сезона · 34 серии" }, poster: "https://i.ytimg.com/vi/TTRAx2ID01c/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=TTRAx2ID01c", watchKind: "youtube", seoSlug: "hotel-grand" },
  { id: 18, title: { hy: "Hotel Grand 2", en: "Hotel Grand 2", ru: "Отель Гранд 2" }, year: "2023", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=WzQRis3gNSc", watchKind: "youtube", seoSlug: "hotel-grand-2" },
  { id: 19, title: { hy: "Hotel Grand 3", en: "Hotel Grand 3", ru: "Отель Гранд 3" }, year: "2023", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=5jh6TU4tI_Y", watchKind: "youtube", seoSlug: "hotel-grand-3" },
  { id: 20, title: { hy: "Մենք փնտրում ենք հարսնացու", en: "We’re Looking for a Bride", ru: "Мы ищем невесту" }, year: "2023", credit: { hy: "48 սերիա", en: "48 episodes", ru: "48 серий" }, kind: "series", episodes: 48, watchUrl: "https://www.youtube.com/watch?v=bSontOUOe6Y", watchKind: "youtube", seoSlug: "looking-for-a-bride" },
  { id: 21, title: { hy: "Իրար դեմ", en: "Against Each Other", ru: "Друг против друга" }, year: "2023", credit: { hy: "114 սերիա", en: "114 episodes", ru: "114 серий" }, kind: "series", episodes: 114, watchUrl: "https://www.youtube.com/watch?v=pR1NupfAP1g", watchKind: "youtube", seoSlug: "against-each-other" },
  { id: 22, title: { hy: "Քո սիրո առաջ", en: "Before Your Love", ru: "Перед твоей любовью" }, year: "2023–2024", credit: { hy: "80 սերիա", en: "80 episodes", ru: "80 серий" }, kind: "series", episodes: 80, watchUrl: "https://kinodaran.com/en/title/in_front_of_your_love.html", watchKind: "platform", seoSlug: "before-your-love" },
  { id: 23, title: { hy: "Մալենա", en: "Malena", ru: "Малена" }, year: "2023", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=7_ZOmSqsbgU", watchKind: "youtube", seoSlug: "malena" },
  { id: 24, title: { hy: "Կախվածություն", en: "Addiction", ru: "Зависимость" }, year: "2023–2024", credit: { hy: "157 սերիա", en: "157 episodes", ru: "157 серий" }, kind: "series", episodes: 157, featuredRank: 5, poster: "https://i.ytimg.com/vi/me9YbbbbY3g/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=me9YbbbbY3g", watchKind: "youtube", seoSlug: "addiction" },
  { id: 25, title: { hy: "Գերիները", en: "The Captives", ru: "Пленники" }, year: "2024", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=U8bqjM4oYpE", watchKind: "youtube", seoSlug: "the-captives" },
  { id: 26, title: { hy: "Սիրելի Սահմի", en: "Dear Sahmi", ru: "Дорогая Сахми" }, year: "2024", credit: { hy: "10 սերիա", en: "10 episodes", ru: "10 серий" }, kind: "series", episodes: 10, featuredRank: 3, poster: "https://i.ytimg.com/vi/vCVZUMun37U/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=vCVZUMun37U", watchKind: "youtube", seoSlug: "dear-sahmi" },
  { id: 27, title: { hy: "Լոս խնամախոս", en: "Los Khnamakhos", ru: "Лос Хнамахос" }, year: "2024", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/los-engagement", watchKind: "platform", seoSlug: "los-khnamakhos" },
  { id: 28, title: { hy: "84-ի ամառը", en: "Summer of ’84", ru: "Лето ’84" }, year: "2024", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, featuredRank: 6, featuredDetail: { hy: "Գաղափար · սցենար · շոուռանինգ · պրոդյուսինգ", en: "Creator · writer · showrunner · producer", ru: "Идея · сценарий · шоураннинг · продюсирование" }, poster: "https://i.ytimg.com/vi/sNbNHBkiCpU/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=sNbNHBkiCpU", watchKind: "youtube", seoSlug: "summer-of-84" },
  { id: 29, title: { hy: "Մտմտիկ և Պրպտիկ", en: "Mtmtik & Prptik", ru: "Мтмтик и Прптик" }, year: "2024", credit: { hy: "Մանկական ֆիլմաշար", en: "Children’s series", ru: "Детский цикл" }, kind: "children", watchUrl: "https://www.youtube.com/@prptik-mtmtik", watchKind: "platform", seoSlug: "mtmtik-prptik" },
  { id: 30, title: { hy: "Եթե ես կրկին պարեի", en: "If I Danced Again", ru: "Если бы я снова танцевала" }, year: "2024–2025", credit: { hy: "26 սերիա", en: "26 episodes", ru: "26 серий" }, kind: "series", episodes: 26, featuredRank: 9, poster: "https://vhx.imgix.net/usatvmax/assets/c8926f74-be03-41c8-8390-2ad705428767.jpg?auto=format%2Ccompress&fit=crop&h=720&w=1280", watchUrl: "https://www.armflix.com/videos/ete-es-krkin-parem-1", watchKind: "platform", seoSlug: "if-i-danced-again" },
  { id: 31, title: { hy: "Սոս Անջելես", en: "Sos Angeles", ru: "Сос Анджелес" }, year: "2024", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/sos-angeles", watchKind: "platform", seoSlug: "sos-angeles" },
  { id: 32, title: { hy: "OKI", en: "OKE", ru: "OKI" }, year: "2024", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=DDosY4yJooE", watchKind: "youtube", seoSlug: "oke" },
  { id: 33, title: { hy: "OKI. Ամանորյա գաղտնիք", en: "OKE: New Year’s Secret", ru: "OKI: Новогодний секрет" }, year: "2024", credit: { hy: "Ֆիլմ", en: "Film", ru: "Фильм" }, kind: "film", watchUrl: "https://ticketsystem.am/hy/event/details/7813", watchKind: "platform", seoSlug: "oke-new-years-secret" },
  { id: 34, title: { hy: "Կայ", en: "Kay", ru: "Кай" }, year: "2024–2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/kay", watchKind: "platform", seoSlug: "kay" },
  { id: 35, title: { hy: "AppSOS", en: "AppSOS", ru: "AppSOS" }, year: "2024–2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/app-sos", watchKind: "platform", seoSlug: "appsos" },
  { id: 36, title: { hy: "Բացահայտված գործեր", en: "Solved Cases", ru: "Раскрытые дела" }, year: "2025", credit: { hy: "116 սերիա", en: "116 episodes", ru: "116 серий" }, kind: "series", episodes: 116, watchUrl: "https://www.youtube.com/watch?v=fZxxqgEjErA", watchKind: "youtube", seoSlug: "solved-cases" },
  { id: 37, title: { hy: "SOSինձ / Սոսինձ", en: "SOSinDz", ru: "SOSмне" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/sos", watchKind: "platform", seoSlug: "sosindz" },
  { id: 38, title: { hy: "Քեզանից հետո", en: "After You", ru: "После тебя" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=elTUhl0v-yc", watchKind: "youtube", seoSlug: "after-you" },
  { id: 39, title: { hy: "Սոսկալի", en: "Soskali", ru: "Соскали" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/soscali", watchKind: "platform", seoSlug: "soskali" },
  { id: 40, title: { hy: "Գնդապետ Սոս", en: "Colonel Sos", ru: "Полковник Сос" }, year: "2025–2026", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=XS5BEogIm7k", watchKind: "youtube", seoSlug: "colonel-sos" },
  { id: 41, title: { hy: "OKI 2", en: "OKE 2", ru: "OKI 2" }, year: "2025–2026", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.tomsarkgh.am/hy/event/49673/Ok%C3%A9-2-1-%D5%AB%D5%B6-%D5%BD%D5%A5%D6%80%D5%AB%D5%A1%D5%B5%D5%AB-%D5%B6%D5%A1%D5%AD%D5%A1%D5%A4%D5%AB%D5%BF%D5%B8%D6%82%D5%B4-%D5%A4%D5%A5%D6%80%D5%A1%D5%BD.html", watchKind: "platform", seoSlug: "oke-2" },
  { id: 42, title: { hy: "Պատերազմից հետո կյանք կա", en: "Life After War", ru: "После войны есть жизнь" }, year: "2026", credit: { hy: "Ներկայացում", en: "Stage play", ru: "Спектакль" }, kind: "stage", watchUrl: "https://www.tomsarkgh.am/hy/event/50596/%D5%8A%D5%A1%D5%BF%D5%A5%D6%80%D5%A1%D5%A6%D5%B4%D5%AB%D6%81-%D5%B0%D5%A5%D5%BF%D5%B8-%D5%AF%D5%B5%D5%A1%D5%B6%D6%84-%D5%AF%D5%A1.html", watchKind: "platform", seoSlug: "life-after-war" },
  { id: 43, title: { hy: "Ճերմակ շապիկ", en: "White Shirt", ru: "Белая рубашка" }, year: "2026", credit: { hy: "Ֆիլմ", en: "Film", ru: "Фильм" }, kind: "film", watchUrl: "https://www.monk3.com/films", watchKind: "platform", seoSlug: "white-shirt" },
  { id: 44, title: { hy: "Բլոկադա", en: "Blockade", ru: "Блокада" }, year: "2026", credit: { hy: "Ներկայացում", en: "Stage play", ru: "Спектакль" }, kind: "stage", featuredRank: 7, poster: "https://i.ytimg.com/vi/yk7S5xIRs1w/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=yk7S5xIRs1w", watchKind: "youtube", seoSlug: "blockade" },
  { id: 45, title: { hy: "Օպերացիա Սոս", en: "Operation Sos", ru: "Операция Сос" }, year: "2026", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/operation-sos", watchKind: "platform", seoSlug: "operation-sos" },
  { id: 46, title: { hy: "Se.La.Vi", en: "Se.La.Vi", ru: "Se.La.Vi" }, year: "2026", credit: { hy: "10 մաս", en: "10 parts", ru: "10 частей" }, kind: "series", episodes: 10, featuredRank: 10, poster: "https://i.ytimg.com/vi/CkbtuC2HHi8/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=CkbtuC2HHi8", watchKind: "youtube", seoSlug: "se-la-vi" },
  { id: 47, title: { hy: "Մի գեղեցիկ օր", en: "Mi Gexecik Or", ru: "Ми Гехецик Ор" }, year: "2026", credit: { hy: "50+ սերիա", en: "50+ episodes", ru: "50+ серий" }, kind: "series", poster: "https://i.ytimg.com/vi/QRCSe3vD3cM/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=QRCSe3vD3cM", watchKind: "youtube", seoSlug: "mi-gexecik-or" },
];

export const locales: Record<Locale, { short: string; label: string; href: string; hrefLang: string }> = {
  hy: { short: "HY", label: "Հայերեն", href: "/", hrefLang: "hy-AM" },
  en: { short: "EN", label: "English", href: "/en/", hrefLang: "en" },
  ru: { short: "RU", label: "Русский", href: "/ru/", hrefLang: "ru" },
};

export { copy, siteLinks, sourceLinks } from "./profile-content.mjs";
