export type Locale = "hy" | "en" | "ru";
export type ProjectKind = "series" | "film" | "stage" | "children";

export type Project = {
  id: number;
  title: Record<Locale, string>;
  year: string;
  credit: Record<Locale, string>;
  kind: ProjectKind;
  episodes?: number;
  featuredRank?: number;
  featuredDetail?: Record<Locale, string>;
  poster?: string;
  watchUrl?: string;
  watchKind?: "youtube" | "platform";
  seoSlug?: string;
};

export const updatedIso = "2026-09-04";

export const projects: Project[] = [
  { id: 1, title: { hy: "Օտարը", en: "The Stranger", ru: "Чужой" }, year: "2017", credit: { hy: "99 սերիա", en: "99 episodes", ru: "99 серий" }, kind: "series", episodes: 99, watchUrl: "https://www.youtube.com/watch?v=T6nt8gOKoso", watchKind: "youtube", seoSlug: "the-stranger" },
  { id: 2, title: { hy: "Էլենի օրագիրը", en: "Elen’s Diary", ru: "Дневник Элен" }, year: "2017–2019", credit: { hy: "197 սերիա", en: "197 episodes", ru: "197 серий" }, kind: "series", episodes: 197, featuredRank: 1, featuredDetail: { hy: "2 եթերաշրջան · 421 սերիա", en: "2 seasons · 421 episodes", ru: "2 сезона · 421 серия" }, poster: "/posters/eleni-oragir.webp", watchUrl: "https://www.youtube.com/playlist?list=PLIdKbEnBj_B-mvF0PArmubgCmqOdv9rvT", watchKind: "youtube", seoSlug: "elens-diary" },
  { id: 3, title: { hy: "Էլենի օրագիրը 2", en: "Elen’s Diary 2", ru: "Дневник Элен 2" }, year: "2018–2019", credit: { hy: "224 սերիա", en: "224 episodes", ru: "224 серии" }, kind: "series", episodes: 224, watchUrl: "https://www.youtube.com/watch?v=J9oQAJIiye8", watchKind: "youtube", seoSlug: "elens-diary-2" },
  { id: 4, title: { hy: "Թղթե երազանք", en: "Paper Dream", ru: "Бумажная мечта" }, year: "2019", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, featuredRank: 2, poster: "/posters/tghte-erazank.webp", watchUrl: "https://www.youtube.com/watch?v=iIn9qu4Phls", watchKind: "youtube", seoSlug: "paper-dream" },
  { id: 5, title: { hy: "Երկուսով", en: "Together", ru: "Вдвоём" }, year: "2019–2021", credit: { hy: "198 սերիա", en: "198 episodes", ru: "198 серий" }, kind: "series", episodes: 198, watchUrl: "https://www.youtube.com/watch?v=O06cuvk73MA", watchKind: "youtube", seoSlug: "together" },
  { id: 6, title: { hy: "Խաղալիք", en: "Toy", ru: "Игрушка" }, year: "2021", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=SOc5x1LOROU", watchKind: "youtube", seoSlug: "toy" },
  { id: 7, title: { hy: "Կհանդիպենք անտառի տնակում", en: "We’ll Meet at the Forest Cottage", ru: "Встретимся в лесном домике" }, year: "2021", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, featuredRank: 8, featuredDetail: { hy: "2 մաս · 48 սերիա", en: "2 parts · 48 episodes", ru: "2 части · 48 серий" }, poster: "/posters/antarri-tnakum.webp", watchUrl: "https://www.youtube.com/watch?v=Q-uiVUBPy5k", watchKind: "youtube", seoSlug: "forest-cottage" },
  { id: 8, title: { hy: "Բեկորներ", en: "Fragments", ru: "Осколки" }, year: "2021–2022", credit: { hy: "148 սերիա", en: "148 episodes", ru: "148 серий" }, kind: "series", episodes: 148, watchUrl: "https://www.youtube.com/watch?v=K3kISoAjN28", watchKind: "youtube", seoSlug: "fragments" },
  { id: 9, title: { hy: "Բռնիր ձեռքս", en: "Hold My Hand", ru: "Держи меня за руку" }, year: "2021–2022", credit: { hy: "120 սերիա", en: "120 episodes", ru: "120 серий" }, kind: "series", episodes: 120, watchUrl: "https://www.youtube.com/watch?v=r_UrgYomjhA", watchKind: "youtube", seoSlug: "hold-my-hand" },
  { id: 10, title: { hy: "Երկու քույր ենք", en: "We Are Two Sisters", ru: "Мы две сестры" }, year: "2022", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=QkCO6N7uK-k", watchKind: "youtube", seoSlug: "we-are-two-sisters" },
  { id: 11, title: { hy: "Հատուկ դասարան", en: "Special Class", ru: "Специальный класс" }, year: "2022", credit: { hy: "90–99 սերիա", en: "90–99 episodes", ru: "90–99 серий" }, kind: "series", featuredRank: 4, featuredDetail: { hy: "2 եթերաշրջան", en: "2 seasons", ru: "2 сезона" }, poster: "/posters/hatuk-dasaran.webp", watchUrl: "https://www.youtube.com/watch?v=IycLc4NiGgk", watchKind: "youtube", seoSlug: "special-class" },
  { id: 12, title: { hy: "Հատուկ դասարան 2", en: "Special Class 2", ru: "Специальный класс 2" }, year: "2022–2023", credit: { hy: "140 սերիա", en: "140 episodes", ru: "140 серий" }, kind: "series", episodes: 140, watchUrl: "https://www.youtube.com/watch?v=qYIl-UJXMIM", watchKind: "youtube", seoSlug: "special-class-2" },
  { id: 13, title: { hy: "Ապրիր ինձ հետ", en: "Live With Me", ru: "Живи со мной" }, year: "2022", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://kinodaran.com/hy/title/aprir_indz_het.html", watchKind: "platform", seoSlug: "live-with-me" },
  { id: 14, title: { hy: "Մնա ինձ հետ", en: "Stay With Me", ru: "Останься со мной" }, year: "2022", credit: { hy: "36 սերիա", en: "36 episodes", ru: "36 серий" }, kind: "series", episodes: 36, watchUrl: "https://kinodaran.com/hy/title/mna_indz_het.html", watchKind: "platform", seoSlug: "stay-with-me" },
  { id: 15, title: { hy: "4 երազանք", en: "4 Dreams", ru: "4 мечты" }, year: "2022–2023", credit: { hy: "61 սերիա", en: "61 episodes", ru: "61 серия" }, kind: "series", episodes: 61, watchUrl: "https://www.youtube.com/watch?v=mFPB0EZOt_A", watchKind: "youtube", seoSlug: "4-dreams" },
  { id: 16, title: { hy: "Կհանդիպենք անտառի տնակում 2", en: "We’ll Meet at the Forest Cottage 2", ru: "Встретимся в лесном домике 2" }, year: "2022–2023", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=TgtC8Rmu9u0", watchKind: "youtube", seoSlug: "forest-cottage-2" },
  { id: 17, title: { hy: "Hotel Grand", en: "Hotel Grand", ru: "Отель Гранд" }, year: "2023", credit: { hy: "10 սերիա", en: "10 episodes", ru: "10 серий" }, kind: "series", episodes: 10, featuredRank: 11, featuredDetail: { hy: "3 եթերաշրջան · 34 սերիա", en: "3 seasons · 34 episodes", ru: "3 сезона · 34 серии" }, poster: "https://i.ytimg.com/vi/TTRAx2ID01c/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=TTRAx2ID01c", watchKind: "youtube", seoSlug: "hotel-grand" },
  { id: 18, title: { hy: "Hotel Grand 2", en: "Hotel Grand 2", ru: "Отель Гранд 2" }, year: "2023", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=WzQRis3gNSc", watchKind: "youtube", seoSlug: "hotel-grand-2" },
  { id: 19, title: { hy: "Hotel Grand 3", en: "Hotel Grand 3", ru: "Отель Гранд 3" }, year: "2023", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=5jh6TU4tI_Y", watchKind: "youtube", seoSlug: "hotel-grand-3" },
  { id: 20, title: { hy: "Մենք փնտրում ենք հարսնացու", en: "We’re Looking for a Bride", ru: "Мы ищем невесту" }, year: "2023", credit: { hy: "48 սերիա", en: "48 episodes", ru: "48 серий" }, kind: "series", episodes: 48, watchUrl: "https://www.youtube.com/watch?v=bSontOUOe6Y", watchKind: "youtube", seoSlug: "looking-for-a-bride" },
  { id: 21, title: { hy: "Իրար դեմ", en: "Against Each Other", ru: "Друг против друга" }, year: "2023", credit: { hy: "114 սերիա", en: "114 episodes", ru: "114 серий" }, kind: "series", episodes: 114, watchUrl: "https://www.youtube.com/watch?v=pR1NupfAP1g", watchKind: "youtube", seoSlug: "against-each-other" },
  { id: 22, title: { hy: "Քո սիրո առաջ", en: "Before Your Love", ru: "Перед твоей любовью" }, year: "2023–2024", credit: { hy: "80 սերիա", en: "80 episodes", ru: "80 серий" }, kind: "series", episodes: 80, watchUrl: "https://kinodaran.com/en/title/in_front_of_your_love.html", watchKind: "platform", seoSlug: "before-your-love" },
  { id: 23, title: { hy: "Մալենա", en: "Malena", ru: "Малена" }, year: "2023", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=7_ZOmSqsbgU", watchKind: "youtube", seoSlug: "malena" },
  { id: 24, title: { hy: "Կախվածություն", en: "Addiction", ru: "Зависимость" }, year: "2023–2024", credit: { hy: "157 սերիա", en: "157 episodes", ru: "157 серий" }, kind: "series", episodes: 157, featuredRank: 5, poster: "https://i.ytimg.com/vi/me9YbbbbY3g/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=me9YbbbbY3g", watchKind: "youtube", seoSlug: "addiction" },
  { id: 25, title: { hy: "Գերիները", en: "The Captives", ru: "Пленники" }, year: "2024", credit: { hy: "24 սերիա", en: "24 episodes", ru: "24 серии" }, kind: "series", episodes: 24, watchUrl: "https://www.youtube.com/watch?v=U8bqjM4oYpE", watchKind: "youtube", seoSlug: "the-captives" },
  { id: 26, title: { hy: "Սիրելի Սահմի", en: "Dear Sahmi", ru: "Дорогая Сахми" }, year: "2024", credit: { hy: "10 սերիա", en: "10 episodes", ru: "10 серий" }, kind: "series", episodes: 10, featuredRank: 3, poster: "https://i.ytimg.com/vi/vCVZUMun37U/hqdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=vCVZUMun37U", watchKind: "youtube", seoSlug: "dear-sahmi" },
  { id: 27, title: { hy: "Լոս խնամախոս", en: "Los Khnamakhos", ru: "Лос Хнамахос" }, year: "2024", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/los-engagement", watchKind: "platform", seoSlug: "los-khnamakhos" },
  { id: 28, title: { hy: "84-ի ամառը", en: "Summer of ’84", ru: "Лето ’84" }, year: "2024", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, featuredRank: 6, featuredDetail: { hy: "Գաղափար · սցենար · շոուռանինգ · պրոդյուսինգ", en: "Creator · writer · showrunner · producer", ru: "Идея · сценарий · шоураннинг · продюсирование" }, poster: "https://i.ytimg.com/vi/sNbNHBkiCpU/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=sNbNHBkiCpU", watchKind: "youtube", seoSlug: "summer-of-84" },
  { id: 29, title: { hy: "Մտմտիկ և Պրպտիկ", en: "Mtmtik & Prptik", ru: "Мтмтик и Прптик" }, year: "2024", credit: { hy: "Մանկական ֆիլմաշար", en: "Children’s series", ru: "Детский цикл" }, kind: "children", watchUrl: "https://www.youtube.com/@prptik-mtmtik", watchKind: "platform", seoSlug: "mtmtik-prptik" },
  { id: 30, title: { hy: "Եթե ես կրկին պարեի", en: "If I Danced Again", ru: "Если бы я снова танцевала" }, year: "2024–2025", credit: { hy: "26 սերիա", en: "26 episodes", ru: "26 серий" }, kind: "series", episodes: 26, featuredRank: 9, poster: "https://vhx.imgix.net/usatvmax/assets/c8926f74-be03-41c8-8390-2ad705428767.jpg?auto=format%2Ccompress&fit=crop&h=720&w=1280", watchUrl: "https://www.armflix.com/videos/ete-es-krkin-parem-1", watchKind: "platform", seoSlug: "if-i-danced-again" },
  { id: 31, title: { hy: "Սոս Անջելես", en: "Sos Angeles", ru: "Сос Анджелес" }, year: "2024", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/sos-angeles", watchKind: "platform", seoSlug: "sos-angeles" },
  { id: 32, title: { hy: "OKI", en: "OKE", ru: "OKI" }, year: "2024", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.youtube.com/watch?v=DDosY4yJooE", watchKind: "youtube", seoSlug: "oke" },
  { id: 33, title: { hy: "OKI. Ամանորյա գաղտնիք", en: "OKE: New Year’s Secret", ru: "OKI: Новогодний секрет" }, year: "2024", credit: { hy: "Ֆիլմ", en: "Film", ru: "Фильм" }, kind: "film", watchUrl: "https://ticketsystem.am/hy/event/details/7813", watchKind: "platform", seoSlug: "oke-new-years-secret" },
  { id: 34, title: { hy: "Կայ", en: "Kay", ru: "Кай" }, year: "2024–2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/kay", watchKind: "platform", seoSlug: "kay" },
  { id: 35, title: { hy: "AppSOS", en: "AppSOS", ru: "AppSOS" }, year: "2024–2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/app-sos", watchKind: "platform", seoSlug: "appsos" },
  { id: 36, title: { hy: "Բացահայտված գործեր", en: "Solved Cases", ru: "Раскрытые дела" }, year: "2025", credit: { hy: "116 սերիա", en: "116 episodes", ru: "116 серий" }, kind: "series", episodes: 116, watchUrl: "https://www.youtube.com/watch?v=fZxxqgEjErA", watchKind: "youtube", seoSlug: "solved-cases" },
  { id: 37, title: { hy: "SOSինձ / Սոսինձ", en: "SOSinDz", ru: "SOSмне" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/sos", watchKind: "platform", seoSlug: "sosindz" },
  { id: 38, title: { hy: "Քեզանից հետո", en: "After You", ru: "После тебя" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=elTUhl0v-yc", watchKind: "youtube", seoSlug: "after-you" },
  { id: 39, title: { hy: "Սոսկալի", en: "Soskali", ru: "Соскали" }, year: "2025", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/soscali", watchKind: "platform", seoSlug: "soskali" },
  { id: 40, title: { hy: "Գնդապետ Սոս", en: "Colonel Sos", ru: "Полковник Сос" }, year: "2025–2026", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.youtube.com/watch?v=XS5BEogIm7k", watchKind: "youtube", seoSlug: "colonel-sos" },
  { id: 41, title: { hy: "OKI 2", en: "OKE 2", ru: "OKI 2" }, year: "2025–2026", credit: { hy: "12 սերիա", en: "12 episodes", ru: "12 серий" }, kind: "series", episodes: 12, watchUrl: "https://www.tomsarkgh.am/hy/event/49673/Ok%C3%A9-2-1-%D5%AB%D5%B6-%D5%BD%D5%A5%D6%80%D5%AB%D5%A1%D5%B5%D5%AB-%D5%B6%D5%A1%D5%AD%D5%A1%D5%A4%D5%AB%D5%BF%D5%B8%D6%82%D5%B4-%D5%A4%D5%A5%D6%80%D5%A1%D5%BD.html", watchKind: "platform", seoSlug: "oke-2" },
  { id: 42, title: { hy: "Պատերազմից հետո կյանք կա", en: "Life After War", ru: "После войны есть жизнь" }, year: "2026", credit: { hy: "Ներկայացում", en: "Stage play", ru: "Спектакль" }, kind: "stage", watchUrl: "https://www.tomsarkgh.am/hy/event/50596/%D5%8A%D5%A1%D5%BF%D5%A5%D6%80%D5%A1%D5%A6%D5%B4%D5%AB%D6%81-%D5%B0%D5%A5%D5%BF%D5%B8-%D5%AF%D5%B5%D5%A1%D5%B6%D6%84-%D5%AF%D5%A1.html", watchKind: "platform", seoSlug: "life-after-war" },
  { id: 43, title: { hy: "Ճերմակ շապիկ", en: "White Shirt", ru: "Белая рубашка" }, year: "2026", credit: { hy: "Ֆիլմ", en: "Film", ru: "Фильм" }, kind: "film", watchUrl: "https://www.monk3.com/films", watchKind: "platform", seoSlug: "white-shirt" },
  { id: 44, title: { hy: "Բլոկադա", en: "Blockade", ru: "Блокада" }, year: "2026", credit: { hy: "Ներկայացում", en: "Stage play", ru: "Спектакль" }, kind: "stage", featuredRank: 7, poster: "https://i.ytimg.com/vi/yk7S5xIRs1w/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=yk7S5xIRs1w", watchKind: "youtube", seoSlug: "blockade" },
  { id: 45, title: { hy: "Օպերացիա Սոս", en: "Operation Sos", ru: "Операция Сос" }, year: "2026", credit: { hy: "16 սերիա", en: "16 episodes", ru: "16 серий" }, kind: "series", episodes: 16, watchUrl: "https://www.armflix.com/operation-sos", watchKind: "platform", seoSlug: "operation-sos" },
  { id: 46, title: { hy: "Se.La.Vi", en: "Se.La.Vi", ru: "Se.La.Vi" }, year: "2026", credit: { hy: "10 մաս", en: "10 parts", ru: "10 частей" }, kind: "series", episodes: 10, featuredRank: 10, poster: "https://i.ytimg.com/vi/CkbtuC2HHi8/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=CkbtuC2HHi8", watchKind: "youtube", seoSlug: "se-la-vi" },
  { id: 47, title: { hy: "Մի գեղեցիկ օր", en: "Mi Gexecik Or", ru: "Ми Гехецик Ор" }, year: "2026", credit: { hy: "50+ սերիա", en: "50+ episodes", ru: "50+ серий" }, kind: "series", poster: "https://i.ytimg.com/vi/QRCSe3vD3cM/maxresdefault.jpg", watchUrl: "https://www.youtube.com/watch?v=QRCSe3vD3cM", watchKind: "youtube", seoSlug: "mi-gexecik-or" },
];

export const locales: Record<Locale, { short: string; label: string; href: string; hrefLang: string }> = {
  hy: { short: "HY", label: "Հայերեն", href: "/", hrefLang: "hy-AM" },
  en: { short: "EN", label: "English", href: "/en/", hrefLang: "en" },
  ru: { short: "RU", label: "Русский", href: "/ru/", hrefLang: "ru" },
};

export const copy = {
  hy: {
    localeName: "Հայերեն",
    nav: { work: "Ընտրված գործեր", filmography: "Ֆիլմագրություն", about: "Մասին", sources: "Աղբյուրներ", contact: "Կապ" },
    primaryNavLabel: "Հիմնական նավարկություն",
    languageNavLabel: "Ընտրել լեզուն",
    eyebrow: "ANI MAGHAKYAN · SELECTED WORKS 2016—2026",
    title: "Անի Մաղաքյան",
    aliases: "ANI MAGHAKYAN · АНИ МАГАКЯН",
    hero: "Պատմություններ, որոնք կյանք են առնում էկրանին։",
    roles: "Սցենարիստ · Շոուռաներ · Պրոդյուսեր · Գրող",
    intro: "Անի Մաղաքյանը հայ սցենարիստ, շոուռաներ, պրոդյուսեր և գրող է։ Նրա առանցքային նախագծերից են «Էլենի օրագիրը», «Թղթե երազանք», «Սիրելի Սահմի», «Հատուկ դասարան», «Կախվածություն», «84-ի ամառը», «Բլոկադա», «Կհանդիպենք անտառի տնակում», «Եթե ես կրկին պարեի», «Se.La.Vi», «Hotel Grand» և «Մի գեղեցիկ օր»։ «84-ի ամառը» նախագծում նա նաև գաղափարի ու սցենարի հեղինակն է, շոուռաները և պրոդյուսերը։ Պաշտոնական ֆիլմագրությունն ընդգրկում է 47 նախագիծ և ավելի քան 2,300 սերիա։",
    imageAlt: "Անի Մաղաքյան՝ հայ սցենարիստ, շոուռաներ և պրոդյուսեր",
    explore: "Բացահայտել ֆիլմագրությունը",
    imdb: "Դիտել IMDb-ում",
    stats: [
      { value: "47", label: "նախագիծ" },
      { value: "2,300+", label: "սերիա" },
      { value: "2016—", label: "սցենարիստական գործունեություն" },
      { value: "4", label: "ձևաչափ" },
    ],
    selectedKicker: "FEATURED / 01",
    selectedTitle: "Ընտրված գործեր",
    selectedIntro: "Կարիերան և հեղինակային դերը լավագույնս ներկայացնող առանցքային նախագծերը։",
    watchYoutube: "Դիտել YouTube-ում",
    openProject: "Բացել նախագծի էջը",
    watchProject: "Դիտել նախագիծը",
    archiveKicker: "ARCHIVE / 02",
    archiveTitle: "Ամբողջական ֆիլմագրություն",
    archiveIntro: "Փնտրեք վերնագրով, տարեթվով կամ ընտրեք ձևաչափը։",
    search: "Փնտրել նախագիծ…",
    filters: { all: "Բոլորը", series: "Սերիալ", film: "Ֆիլմ", stage: "Ներկայացում", children: "Մանկական" },
    table: { number: "№", project: "Նախագիծ", year: "Թվական", format: "Ձևաչափ / ծավալ" },
    results: "արդյունք",
    noResults: "Այս որոնմամբ նախագիծ չի գտնվել։",
    aboutKicker: "PROFILE / 03",
    aboutTitle: "Հեղինակի մասին",
    bio: "Անի Համլետի Մաղաքյանը (ծնված 1988 թվականի հունիսի 3-ին, Վանաձոր) հայ սցենարիստ, արձակագիր, լրագրող և մանկավարժ է։ 16 տարեկանից գրում է արձակ ու աշխատում որպես լրագրող։ Հեղինակել է ավելի քան 700 հոդված, հարցազրույց և պատմվածք։ Սցենարիստական մասնագիտական գործունեությունը սկսել է 2016 թվականին։",
    philosophy: "Նրա գործերում դրաման ու հումորը ապրում են նույն տարածքում, իսկ հերոսները չեն բաժանվում պարզ «լավերի» ու «վատերի»։ Պատմությունը կառուցվում է ավարտից դեպի սկիզբ՝ հստակ դրամատուրգիական հիմքով։",
    educationTitle: "Կրթություն և մասնագիտական զարգացում",
    education: [
      "Հայոց լեզվի և գրականության ուսուցիչ",
      "Կովկասյան ինստիտուտ — քաղաքագիտություն և լրագրություն, մագիստրատուրա",
      "Ալեքսանդր Միտտայի կինոդպրոց, Մոսկվա — ֆիլմի և հեռուստատեսության սցենար",
      "Ռիչարդ Քրևելին — Storytelling for Cinema and TV",
      "Քրիստոֆեր Վոգլեր — The Hero’s Journey",
    ],
    practiceTitle: "Ստեղծագործական պրակտիկա",
    practice: ["Գաղափարի և պատմության ճարտարապետություն", "Սցենարային սենյակի ղեկավարում", "Շոուռաներական և ստեղծագործական վերահսկողություն", "Սերիալ · ֆիլմ · պիես · մանկական պատմություն"],
    booksTitle: "Գրքեր",
    books: ["«Ժամանակավոր կանգառ» — պատմվածքների ժողովածու, 2010", "«Տակնուվրա. Մի օրում բոլորը վերադառնում են» — վեպ, 2021"],
    sourcesKicker: "EVIDENCE / 04",
    sourcesTitle: "Աղբյուրներ և հաստատումներ",
    sourcesIntro: "Կենսագրական տվյալները, հարցազրույցները և ընտրված նախագծերի հեղինակային տվյալները համադրվել են հրապարակային, անկախ և ոլորտային աղբյուրների հետ։",
    sourcesMethod: "Արխիվային նշում․ կայքն առանձնացնում է պաշտոնական սոցիալական էջերը, մասնագիտական շտեմարանները և անկախ խմբագրական հրապարակումները։ Յուրաքանչյուր հղում հաստատում է տվյալ աղբյուրում ներկայացված տեղեկությունը, ոչ թե ամբողջ ֆիլմագրությունը։",
    visitSource: "Բացել աղբյուրը",
    faqKicker: "ANSWERS / 05",
    faqTitle: "Հաճախ տրվող հարցեր",
    faqs: [
      { q: "Ո՞վ է Անի Մաղաքյանը։", a: "Անի Մաղաքյանը հայ սցենարիստ, շոուռաներ, պրոդյուսեր, արձակագիր և լրագրող է, որը 2016 թվականից ստեղծում է հեռուստասերիալներ, ֆիլմեր, պիեսներ ու մանկական նախագծեր։" },
      { q: "Քանի՞ նախագիծ է ներառում ֆիլմագրությունը։", a: "Պաշտոնական ֆիլմագրությունն ընդգրկում է 47 նախագիծ և ավելի քան 2,300 սերիա, ինչպես նաև ֆիլմեր, ներկայացումներ ու մանկական աշխատանքներ։" },
      { q: "Որո՞նք են Անի Մաղաքյանի առանցքային նախագծերը։", a: "«Էլենի օրագիր», «Թղթե երազանք», «Սիրելի Սահմի», «Հատուկ դասարան», «Կախվածություն», «84-ի ամառը», «Բլոկադա», «Կհանդիպենք անտառի տնակում», «Եթե ես կրկին պարեի», «Se.La.Vi», «Hotel Grand» և «Մի գեղեցիկ օր»։" },
      { q: "Ի՞նչ դեր է ունեցել Անին «84-ի ամառը» նախագծում։", a: "«84-ի ամառը» Անի Մաղաքյանի հեղինակային նախագիծն է․ նա գաղափարի ու սցենարի հեղինակն է, շոուռաները և պրոդյուսերը։ Նախագիծն ամբողջությամբ արտադրվել է նրա թիմի կողմից՝ որպես այլ հարթակի համար իրականացված աութսորս արտադրություն։" },
    ],
    contactKicker: "CONTACT / 06",
    contactTitle: "Մի պատմություն սկսենք։",
    contactText: "Համագործակցություն, սցենարի մշակում, շոուռաներական աշխատանք կամ ստեղծագործական պրոդյուսինգ։",
    contactButton: "Կապվել Maghakian Scripts-ի հետ",
    sources: "Աղբյուրներ և պրոֆիլներ",
    updated: "Թարմացված՝ 4 սեպտեմբերի, 2026",
    backTop: "Վերև",
  },
  en: {
    localeName: "English",
    nav: { work: "Selected work", filmography: "Filmography", about: "About", sources: "Sources", contact: "Contact" },
    primaryNavLabel: "Primary navigation",
    languageNavLabel: "Choose language",
    eyebrow: "ANI MAGHAKYAN · SELECTED WORKS 2016—2026",
    title: "Ani Maghakyan",
    aliases: "ԱՆԻ ՄԱՂԱՔՅԱՆ · АНИ МАГАКЯН",
    hero: "Stories built to live on screen.",
    roles: "Screenwriter · Showrunner · Producer · Author",
    intro: "Ani Maghakyan is an Armenian screenwriter, showrunner and producer whose credits include Elen’s Diary, Paper Dream, Special Class, Addiction, Summer of ’84 and Mi Gexecik Or («Մի գեղեցիկ օր»). Her official archive lists 47 projects and more than 2,300 identified episodes.",
    imageAlt: "Ani Maghakyan — official filmography of the Armenian screenwriter",
    explore: "Explore the filmography",
    imdb: "View on IMDb",
    stats: [
      { value: "47", label: "projects" },
      { value: "2,300+", label: "listed episodes" },
      { value: "2016—", label: "screenwriting career" },
      { value: "4", label: "formats" },
    ],
    selectedKicker: "FEATURED / 01",
    selectedTitle: "Selected work",
    selectedIntro: "The defining projects that best represent her career and authorship.",
    watchYoutube: "Watch on YouTube",
    openProject: "Open project page",
    watchProject: "Watch project",
    archiveKicker: "ARCHIVE / 02",
    archiveTitle: "Complete filmography",
    archiveIntro: "Search by title or year, or filter the archive by format.",
    search: "Search projects…",
    filters: { all: "All", series: "Series", film: "Film", stage: "Stage", children: "Children" },
    table: { number: "#", project: "Project", year: "Year", format: "Format / volume" },
    results: "results",
    noResults: "No project matches this search.",
    aboutKicker: "PROFILE / 03",
    aboutTitle: "About the writer",
    bio: "Ani Hamlet Maghakyan (born June 3, 1988, in Vanadzor, Armenia) is an Armenian screenwriter, prose writer, journalist and educator. She began writing prose and working as a journalist at sixteen, and has authored more than 700 articles, interviews and short stories. Her professional screenwriting career began in 2016.",
    philosophy: "Her work lets drama and humour occupy the same frame, while characters resist simple divisions into heroes and villains. Each story is engineered from its ending backwards, with a clear dramatic foundation.",
    educationTitle: "Education & professional development",
    education: [
      "Teacher of Armenian Language and Literature",
      "Caucasus Institute — MA in Political Science and Journalism",
      "Alexander Mitta Film School, Moscow — Film and Television Screenwriting",
      "Richard Krevolin — Storytelling for Cinema and TV",
      "Christopher Vogler — The Hero’s Journey",
    ],
    practiceTitle: "Creative practice",
    practice: ["Concept and story architecture", "Writers’ room leadership", "Showrunning and creative oversight", "Series · film · stage · children’s stories"],
    booksTitle: "Books",
    books: ["Temporary Stop — short-story collection, 2010", "Topsy-Turvy: Everyone Returns in One Day — novel, 2021"],
    sourcesKicker: "EVIDENCE / 04",
    sourcesTitle: "Sources & verification",
    sourcesIntro: "Biographical facts, interviews and selected creative credits are cross-referenced with public, independent and industry sources.",
    sourcesMethod: "Archive note: official social profiles, professional databases and independent editorial coverage are identified separately. A link supports the fact it covers; it does not certify the entire filmography.",
    visitSource: "Open source",
    faqKicker: "ANSWERS / 05",
    faqTitle: "Frequently asked questions",
    faqs: [
      { q: "Who is Ani Maghakyan?", a: "An Armenian screenwriter, showrunner, producer, prose writer and journalist creating television series, films, plays and children’s projects since 2016." },
      { q: "How many projects are in the filmography?", a: "This archive lists 47 projects and more than 2,300 identified episodes, alongside films, stage plays and children’s work." },
      { q: "Which are Ani Maghakyan’s key projects?", a: "Elen’s Diary, Paper Dream, Dear Sahmi, Special Class, Addiction, Summer of ’84, Blockade, We’ll Meet at the Forest Cottage, If I Danced Again, Se.La.Vi, Hotel Grand and Mi Gexecik Or («Մի գեղեցիկ օր»)." },
      { q: "What was Ani Maghakyan’s role in Summer of ’84?", a: "Summer of ’84 is an Ani Maghakyan creator-led project: she originated the idea, wrote the screenplay, and served as showrunner and producer while delivering the production as an outsourced project for another platform." },
    ],
    contactKicker: "CONTACT / 06",
    contactTitle: "Let’s begin a story.",
    contactText: "For collaboration, story development, showrunning or creative production.",
    contactButton: "Contact Maghakian Scripts",
    sources: "Sources & profiles",
    updated: "Updated September 4, 2026",
    backTop: "Back to top",
  },
  ru: {
    localeName: "Русский",
    nav: { work: "Избранное", filmography: "Фильмография", about: "Об авторе", sources: "Источники", contact: "Контакты" },
    primaryNavLabel: "Основная навигация",
    languageNavLabel: "Выбрать язык",
    eyebrow: "ANI MAGHAKYAN · SELECTED WORKS 2016—2026",
    title: "Ани Магакян",
    aliases: "ԱՆԻ ՄԱՂԱՔՅԱՆ · ANI MAGHAKYAN",
    hero: "Истории, созданные для экрана.",
    roles: "Сценарист · Шоураннер · Продюсер · Писатель",
    intro: "Ани Магакян — армянский сценарист, шоураннер и продюсер, автор проектов «Дневник Элен», «Бумажная мечта», «Специальный класс», «Зависимость», «Лето ’84» и Mi Gexecik Or («Մի գեղեցիկ օր»). Официальный архив включает 47 проектов и более 2 300 указанных серий.",
    imageAlt: "Ани Магакян — официальная фильмография армянского сценариста",
    explore: "Открыть фильмографию",
    imdb: "Смотреть на IMDb",
    stats: [
      { value: "47", label: "проектов" },
      { value: "2 300+", label: "указанных серий" },
      { value: "2016—", label: "сценарная карьера" },
      { value: "4", label: "формата" },
    ],
    selectedKicker: "FEATURED / 01",
    selectedTitle: "Избранные работы",
    selectedIntro: "Ключевые проекты, наиболее полно представляющие её карьеру и авторский вклад.",
    watchYoutube: "Смотреть на YouTube",
    openProject: "Открыть страницу проекта",
    watchProject: "Смотреть проект",
    archiveKicker: "ARCHIVE / 02",
    archiveTitle: "Полная фильмография",
    archiveIntro: "Ищите по названию или году либо выберите нужный формат.",
    search: "Найти проект…",
    filters: { all: "Все", series: "Сериал", film: "Фильм", stage: "Спектакль", children: "Детское" },
    table: { number: "№", project: "Проект", year: "Год", format: "Формат / объём" },
    results: "результатов",
    noResults: "По этому запросу проекты не найдены.",
    aboutKicker: "PROFILE / 03",
    aboutTitle: "Об авторе",
    bio: "Ани Гамлетовна Магакян (родилась 3 июня 1988 года в Ванадзоре, Армения) — армянский сценарист, прозаик, журналист и педагог. С шестнадцати лет пишет прозу и работает в журналистике; автор более 700 статей, интервью и рассказов. Профессиональную сценарную деятельность начала в 2016 году.",
    philosophy: "В её работах драма и юмор существуют в одном пространстве, а персонажи не делятся на простых «хороших» и «плохих». История выстраивается от финала к началу — на ясной драматургической основе.",
    educationTitle: "Образование и профессиональное развитие",
    education: [
      "Учитель армянского языка и литературы",
      "Кавказский институт — магистратура по политологии и журналистике",
      "Киношкола Александра Митты, Москва — сценарий кино и телевидения",
      "Ричард Креволин — Storytelling for Cinema and TV",
      "Кристофер Воглер — The Hero’s Journey",
    ],
    practiceTitle: "Творческая практика",
    practice: ["Концепция и архитектура истории", "Руководство сценарной комнатой", "Шоураннинг и творческий контроль", "Сериал · фильм · пьеса · детская история"],
    booksTitle: "Книги",
    books: ["«Временная остановка» — сборник рассказов, 2010", "«Вверх дном. За один день возвращаются все» — роман, 2021"],
    sourcesKicker: "EVIDENCE / 04",
    sourcesTitle: "Источники и подтверждения",
    sourcesIntro: "Биографические сведения, интервью и отдельные творческие титры сопоставлены с публичными, независимыми и отраслевыми источниками.",
    sourcesMethod: "Примечание архива: официальные социальные профили, профессиональные базы и независимые редакционные публикации отмечены отдельно. Ссылка подтверждает конкретные сведения источника, а не всю фильмографию целиком.",
    visitSource: "Открыть источник",
    faqKicker: "ANSWERS / 05",
    faqTitle: "Частые вопросы",
    faqs: [
      { q: "Кто такая Ани Магакян?", a: "Армянский сценарист, шоураннер, продюсер, прозаик и журналист, создающая телесериалы, фильмы, пьесы и детские проекты с 2016 года." },
      { q: "Сколько проектов входит в фильмографию?", a: "Архив включает 47 проектов и более 2 300 указанных серий, а также фильмы, спектакли и детские работы." },
      { q: "Какие проекты Ани Магакян являются ключевыми?", a: "«Дневник Элен», «Бумажная мечта», «Дорогая Сахми», «Специальный класс», «Зависимость», «Лето ’84», «Блокада», «Встретимся в лесном домике», «Если бы я снова танцевала», Se.La.Vi, «Отель Гранд» и Mi Gexecik Or («Մի գեղեցիկ օր»)." },
      { q: "Какую роль Ани Магакян выполняла в проекте «Лето ’84»?", a: "«Лето ’84» — авторский проект Ани Магакян: ей принадлежат идея и сценарий; в производстве она также выступила шоураннером и продюсером, реализовав проект в формате аутсорсинга для другой платформы." },
    ],
    contactKicker: "CONTACT / 06",
    contactTitle: "Начнём новую историю.",
    contactText: "Для сотрудничества, разработки сценария, шоураннинга и креативного продюсирования.",
    contactButton: "Связаться с Maghakian Scripts",
    sources: "Источники и профили",
    updated: "Обновлено 4 сентября 2026",
    backTop: "Наверх",
  },
} satisfies Record<Locale, Record<string, unknown>>;

export const siteLinks = {
  imdb: "https://www.imdb.com/name/nm9250160/",
  instagram: "https://www.instagram.com/maghakianscripts/",
  personalInstagram: "https://www.instagram.com/ani_maghaqia/",
  interview: "https://style.news.am/arm/news/70076/ete-uzum-eq-stextsagortsel-eleni-oragiry-erkusov-ev-ayl-haytni-serialneri-scenarist-ani-maxaqyany-tchisht-patmutyun-yntrelu-ev-ayn-hetaqrqir-pahelu-masin.html",
  kinopoisk: "https://www.kinopoisk.ru/name/5444828/",
  elcinema: "https://elcinema.com/en/person/2161108/",
};

export const sourceLinks = [
  {
    id: 1,
    label: "IMDb",
    href: siteLinks.imdb,
    kind: { hy: "Մասնագիտական շտեմարան", en: "Industry database", ru: "Профессиональная база" },
    note: { hy: "Գրողի պրոֆիլ և ընտրված էկրանային աշխատանքներ", en: "Writer profile and selected screen credits", ru: "Профиль автора и избранные экранные работы" },
  },
  {
    id: 2,
    label: "Armenian Museum of Moscow",
    href: "https://www.armmuseum.ru/news-blog/ani-maghakyan-interview",
    kind: { hy: "Խորքային հարցազրույց", en: "In-depth interview", ru: "Большое интервью" },
    note: { hy: "Կրթություն, լրագրություն, կարիերայի սկիզբ և ստեղծագործական մոտեցում", en: "Education, journalism, career beginnings and creative process", ru: "Образование, журналистика, начало карьеры и творческий метод" },
  },
  {
    id: 3,
    label: "NEWS.am Style",
    href: siteLinks.interview,
    kind: { hy: "Հեղինակային հարցազրույց", en: "Editorial interview", ru: "Редакционное интервью" },
    note: { hy: "Պատմության ընտրություն, դրամատուրգիա և սերիալային աշխատանք", en: "Story selection, dramatic structure and series writing", ru: "Выбор истории, драматургия и работа над сериалами" },
  },
  {
    id: 4,
    label: "Sputnik Armenia",
    href: "https://am.sputniknews.ru/20251217/blokada-novaya-postanovka-o-karabakhskikh-sobytiyakh-96979633.html",
    kind: { hy: "Մշակութային լրատվություն", en: "Cultural reporting", ru: "Культурная публикация" },
    note: { hy: "«Բլոկադա» ներկայացման սցենարային հեղինակություն", en: "Screenwriting credit for the stage production Blockade", ru: "Авторство сценария спектакля «Блокада»" },
  },
  {
    id: 5,
    label: "Abril Books",
    href: "https://abrilbooks.com/creator/ani-maghakyan/",
    kind: { hy: "Հրատարակչական կատալոգ", en: "Bookseller catalogue", ru: "Книжный каталог" },
    note: { hy: "Անի Մաղաքյանի հեղինակային էջ և «Տակնուվրա» գիրքը", en: "Author page and the book Taknuvra", ru: "Страница автора и книга «Такнувра»" },
  },
  {
    id: 6,
    label: "Okko",
    href: "https://okko.tv/media/selections/sitkomy-i-dramy-samye-zametnye-armyanskie-serialy",
    kind: { hy: "Ոլորտային ընտրանի", en: "Industry editorial", ru: "Отраслевая подборка" },
    note: { hy: "«84-ի ամառը» և «Էլենի օրագիր» աշխատանքների հիշատակում", en: "Coverage of Summer of ’84 and Elen’s Diary", ru: "Упоминание «Лета ’84» и «Дневника Элен»" },
  },
  {
    id: 7,
    label: "Oragir News",
    href: "https://oragir.news/hy/material/2026/06/28/200446",
    kind: { hy: "2026 հարցազրույց", en: "2026 editorial interview", ru: "Интервью 2026" },
    note: { hy: "Անի Մաղաքյանի կարիերան, «Էլենի օրագիրը», Se.La.Vi և նոր «Մի գեղեցիկ օր» նախագիծը", en: "Ani Maghakyan's career, Elen's Diary, Se.La.Vi and the 2026 series Mi Gexecik Or", ru: "Карьера Ани Магакян, «Дневник Элен», Se.La.Vi и сериал 2026 года «Մի գեղեցիկ օր»" },
  },
  {
    id: 8,
    label: "SHANT TV Armenia",
    href: "https://www.youtube.com/watch?v=TanQYxqlKQ0",
    kind: { hy: "Պաշտոնական հեռուստաալիք", en: "Official broadcaster", ru: "Официальный телеканал" },
    note: { hy: "«Մի գեղեցիկ օր» նախագծի ստեղծման և թեմաների ներկայացում՝ սցենարիստի մասնակցությամբ", en: "Official broadcaster coverage of Mi Gexecik Or with the screenwriter participating", ru: "Материал официального телеканала о «Մի գեղեցիկ օր» с участием сценариста" },
  },
  {
    id: 9,
    label: "KinoPoisk",
    href: siteLinks.kinopoisk,
    kind: { hy: "Կինոյի մասնագիտական շտեմարան", en: "Film industry database", ru: "Кинобаза" },
    note: { hy: "Անի Մաղաքյանի մասնագիտական էջ և ընտրված ֆիլմագրություն", en: "Ani Maghakyan profile and selected screen credits", ru: "Профиль Ани Магакян и избранная фильмография" },
  },
  {
    id: 10,
    label: "elCinema",
    href: siteLinks.elcinema,
    kind: { hy: "Միջազգային կինոշտեմարան", en: "International film database", ru: "Международная кинобаза" },
    note: { hy: "Միջազգային պրոֆիլ և «Թղթե երազանք» նախագծի հեղինակային կապ", en: "International profile and writer credit for Paper Dream", ru: "Международный профиль и сценарный титр «Бумажной мечты»" },
  },
] as const;
