import { escapeHtml as e } from './studio.mjs';
export const inquiryCopy = {
  hy:{name:'Անուն',email:'Էլ․ հասցե',type:'Նախագծի տեսակ',brief:'Պատմեք նախագծի մասին',company:'Ընկերություն',optional:'Ընտրովի մանրամասներ',stage:'Աշխատանքի փուլ',timeline:'Ցանկալի ժամկետ',budget:'Բյուջեի շրջանակ',choose:'Ընտրել',types:['Ֆիլմ','Սերիալ','Պատմության մշակում','Շոուռանինգ','Ստեղծագործական պրոդյուսինգ','Այլ'],stages:['Գաղափար','Թրիթմենթ','Առկա սցենար','Մշակում','Նախապատրաստում','Արտադրություն'],review:'Դիտել հայտը',back:'Խմբագրել',send:'Ուղարկել էլ․ փոստով',copy:'Պատճենել հայտը',download:'Ներբեռնել հայտը',note:'Հայտը պատրաստվում է ձեր սարքում։ Հաջորդ քայլում կբացվի ձեր էլ․ փոստը, որտեղից կարող եք ուղարկել այն։',reviewTitle:'Ստուգեք ձեր հայտը',reviewNote:'Հայտը դեռ ուղարկված չէ։ Ուղարկեք այն ձեր էլ․ փոստից։ Եթե փոստային ծրագիրը չի բացվում, պատճենեք հայտը և ուղարկեք նշված հասցեին։',copied:'Հայտը պատճենված է։',copyFailed:'Պատճենումը չհաջողվեց։ Ներբեռնեք հայտը կամ ընտրեք և պատճենեք տեքստը։',required:'Լրացրեք այս դաշտը։',invalidEmail:'Մուտքագրեք վավեր էլ․ հասցե։',subject:'Նախագծի հայտ — Maghakian Scripts',nojs:'Նախագծի նկարագրությունն ուղարկեք էլ․ փոստով։'},
  en:{name:'Name',email:'Email',type:'Project type',brief:'Tell us about the project',company:'Company',optional:'Optional details',stage:'Development stage',timeline:'Desired timeframe',budget:'Budget range',choose:'Choose',types:['Film','Series','Story development','Showrunning','Creative production','Other'],stages:['Idea','Treatment','Existing script','Development','Pre-production','Production'],review:'Review brief',back:'Edit brief',send:'Send brief by email',copy:'Copy brief',download:'Download brief',note:'Your brief is prepared on your device. The next step opens your email app so you can send it.',reviewTitle:'Review your brief',reviewNote:'Your inquiry has not been sent yet. Send it from your email app. If the app does not open, copy the brief and email it to the address below.',copied:'Brief copied.',copyFailed:'Could not copy. Download the brief or select and copy the text.',required:'Complete this field.',invalidEmail:'Enter a valid email address.',subject:'Project inquiry — Maghakian Scripts',nojs:'Email your project description to us.'},
  ru:{name:'Имя',email:'Электронная почта',type:'Тип проекта',brief:'Расскажите о проекте',company:'Компания',optional:'Дополнительные сведения',stage:'Этап работы',timeline:'Желаемые сроки',budget:'Диапазон бюджета',choose:'Выбрать',types:['Фильм','Сериал','Разработка истории','Шоураннинг','Творческое продюсирование','Другое'],stages:['Идея','Тритмент','Готовый сценарий','Разработка','Подготовка','Производство'],review:'Проверить заявку',back:'Редактировать',send:'Отправить по почте',copy:'Скопировать заявку',download:'Скачать заявку',note:'Заявка готовится на вашем устройстве. На следующем шаге откроется почтовое приложение, из которого вы сможете её отправить.',reviewTitle:'Проверьте заявку',reviewNote:'Заявка ещё не отправлена. Отправьте её из почтового приложения. Если оно не открывается, скопируйте текст и отправьте его на адрес ниже.',copied:'Заявка скопирована.',copyFailed:'Не удалось скопировать. Скачайте заявку или выделите и скопируйте текст.',required:'Заполните это поле.',invalidEmail:'Введите корректный адрес электронной почты.',subject:'Заявка на проект — Maghakian Scripts',nojs:'Отправьте описание проекта по электронной почте.'},
};
export function inquiryForm(locale, email) {
  const t=inquiryCopy[locale];
  const field=(name,label,type='text',required=false)=>`<div class="inquiry-field"><label for="inquiry-${name}">${label}${required?' *':''}</label><input id="inquiry-${name}" name="${name}" type="${type}" maxlength="${type==='email'?254:120}" autocomplete="${{name:'name',email:'email',company:'organization'}[name]||'off'}" ${required?'required':''} aria-describedby="error-${name}"><span class="field-error" id="error-${name}"></span></div>`;
  const select=(name,label,options,required=false)=>`<div class="inquiry-field"><label for="inquiry-${name}">${label}${required?' *':''}</label><select id="inquiry-${name}" name="${name}" ${required?'required':''} aria-describedby="error-${name}"><option value="">${t.choose}</option>${options.map(v=>`<option>${v}</option>`).join('')}</select><span class="field-error" id="error-${name}"></span></div>`;
  return `<section class="project-inquiry" data-inquiry data-locale="${locale}" data-copy="${e(JSON.stringify(t))}" data-email="${e(email)}"><p class="inquiry-note">${t.note}</p><form class="inquiry-form" hidden novalidate><div class="inquiry-fields">${field('name',t.name,'text',true)}${field('email',t.email,'email',true)}${select('type',t.type,t.types,true)}</div><div class="inquiry-field"><label for="inquiry-brief">${t.brief} *</label><textarea id="inquiry-brief" name="brief" rows="7" maxlength="3000" required aria-describedby="error-brief"></textarea><span class="field-error" id="error-brief"></span></div><details class="inquiry-details"><summary>${t.optional}</summary><div class="inquiry-fields">${field('company',t.company)}${select('stage',t.stage,t.stages)}${field('timeline',t.timeline)}${field('budget',t.budget)}</div></details><button class="primary-action" type="submit">${t.review}</button></form><div class="inquiry-review" hidden><h2 tabindex="-1">${t.reviewTitle}</h2><p>${t.reviewNote}</p><pre class="brief-preview"></pre><div class="cta"><a class="primary-action" data-send-brief>${t.send}</a><button class="secondary-action" type="button" data-edit-brief>${t.back}</button><button class="secondary-action" type="button" data-copy-brief>${t.copy}</button><button class="secondary-action" type="button" data-download-brief>${t.download}</button></div><p class="inquiry-status" role="status" aria-live="polite"></p></div><p><a href="mailto:${e(email)}">${e(email)}</a></p><noscript><p>${t.nojs}</p></noscript></section>`;
}
