// Shared brand and navigation for React-rendered and generated static pages.
export const studioCopy = {
  hy: {home:'Գլխավոր',work:'Աշխատանքներ',services:'Ծառայություններ',founder:'Հիմնադիր',writing:'Գրականություն',archive:'Արխիվ',press:'Հարցազրույցներ',books:'Գրքեր',start:'Սկսել նախագիծ',menu:'Բացել ընտրացանկը',languages:'Ընտրել լեզուն',headline:'Պատմությունը սկսվում է այստեղ։',intro:'Maghakian Scripts՝ Անի Մաղաքյանի հիմնադրած սցենարական ստուդիա։ Սցենարագրություն, պատմության մշակում, շոուռանինգ և ստեղծագործական պրոդյուսինգ։',founderRole:'Հիմնադիր և ստեղծագործական ղեկավար',founded:'Հիմնադիր՝ Անի Մաղաքյան',selected:'Ընտրված աշխատանքներ',serviceIntro:'Գաղափարի մշակումից մինչև սցենար և ստեղծագործական ղեկավարում։',contactIntro:'Պատմեք նախագծի և անհրաժեշտ աջակցության մասին։ Սկսելու համար բավական է կարճ նկարագրությունը։'},
  en: {home:'Home',work:'Work',services:'Services',founder:'Founder',writing:'Writing',archive:'Archive',press:'Interviews',books:'Books',start:'Start a Project',menu:'Open menu',languages:'Choose language',headline:'The story starts here.',intro:'Maghakian Scripts is a screenwriting studio founded by Ani Maghakyan. Screenwriting, story development, showrunning and creative production.',founderRole:'Founder & Creative Lead',founded:'Founded by Ani Maghakyan',selected:'Selected Work',serviceIntro:'From shaping an idea to writing the script and leading its creative development.',contactIntro:'Tell us about your project and the support you need. A short description is enough to begin.'},
  ru: {home:'Главная',work:'Работы',services:'Услуги',founder:'Основатель',writing:'Литература',archive:'Архив',press:'Интервью',books:'Книги',start:'Начать проект',menu:'Открыть меню',languages:'Выбрать язык',headline:'История начинается здесь.',intro:'Maghakian Scripts — сценарная студия, основанная Ани Магакян. Сценарии, разработка историй, шоураннинг и творческое продюсирование.',founderRole:'Основатель и творческий руководитель',founded:'Основатель — Ани Магакян',selected:'Избранные работы',serviceIntro:'От разработки идеи до сценария и творческого руководства проектом.',contactIntro:'Расскажите о проекте и необходимой поддержке. Для начала достаточно короткого описания.'},
};
export const escapeHtml = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function studioPath(locale, basePath = '', tail = '') {
  return `${basePath}/${locale === 'hy' ? '' : `${locale}/`}${tail ? `${tail.replace(/\/$/,'')}/` : ''}`;
}
export function studioHeader(locale, basePath = '', tail = '') {
  const t = studioCopy[locale];
  const links = [['projects',t.work],['services',t.services],['about',t.founder],['writings',t.writing],['work-with-ani',t.start]];
  const nav = links.map(([path,label])=>`<a href="${studioPath(locale,basePath,path)}"${tail === path ? ' aria-current="page"' : ''}${path === 'work-with-ani' ? ' class="nav-inquiry" data-track="start_project"' : ''}>${label}</a>`).join('');
  const languages = ['hy','en','ru'].map(code=>`<a href="${studioPath(code,basePath,tail)}" hreflang="${code === 'hy' ? 'hy-AM' : code}" lang="${code}" aria-label="${{hy:'Հայերեն',en:'English',ru:'Русский'}[code]}"${code === locale ? ' aria-current="page"' : ''}>${code.toUpperCase()}</a>`).join('');
  const extra = [['books',t.books],['press',t.press]].map(([path,label])=>`<a href="${studioPath(locale,basePath,path)}">${label}</a>`).join('');
  return `<a class="brand" href="${studioPath(locale,basePath)}" aria-label="Maghakian Scripts — ${t.home}"><img src="${basePath}/brand/maghakian-scripts-light.svg" alt="Maghakian Scripts" width="1230" height="390" fetchpriority="high"></a><nav class="topnav" aria-label="${t.menu}">${nav}</nav><nav class="languages" aria-label="${t.languages}">${languages}</nav><details class="mobile-menu"><summary aria-label="${t.menu}"><span class="menu-icon" aria-hidden="true"></span></summary><nav aria-label="${t.menu}"><div class="mobile-language-options" role="group" aria-label="${t.languages}">${languages}</div>${nav}${extra}<a href="${studioPath(locale,basePath)}#filmography">${t.archive}</a></nav></details>`;
}
export function studioFooter(locale, basePath = '') {
  const t = studioCopy[locale];
  return `<a class="footer-brand" href="${studioPath(locale,basePath)}">Maghakian Scripts</a><p>${t.founded}</p><nav class="footer-nav" aria-label="${t.menu}">${[['projects',t.work],['services',t.services],['about',t.founder],['books',t.books],['writings',t.writing],['press',t.press],['work-with-ani',t.start]].map(([path,label])=>`<a href="${studioPath(locale,basePath,path)}">${label}</a>`).join('')}</nav>`;
}
